name: Quests
main: me.blackvein.quests.Quests
version: ${project.version}-b${env.BUILD_NUMBER}
api-version: 1.13
description: An extensive questing system.
website: https://www.spigotmc.org/resources/quests.3711/
dev-url: https://github.com/PikaMug/Quests
author: PikaMug
softdepend: [Citizens, CitizensBooks, Denizen, DungeonsXL, GPS, Heroes, mcMMO, Parties, PhatLoots, PlaceholderAPI, Vault, WorldGuard]
permissions:
    quests.quest:
        description: View current quest objectives
        default: true
    quests.questinfo:
        description: View information about a quest
        default: true
    quests.quests:
        description: Display plugin help
        default: true
    quests.list:
        description: List available quests
        default: true
    quests.take:
        description: Accept a quest via command
        default: true
    quests.quit:
        description: Quit a current quest
        default: true
    quests.stats:
        description: View quest statistics
        default: true
    quests.top:
        description: View plugin leaderboards
        default: true
    quests.info:
        description: View plugin information
        default: true
    quests.journal:
        description: Toggle the Quest Journal
        default: true
    quests.compass:
        description: Use a Compass to target quests
        default: true
    quests.admin:
        description: Display administrator help
        default: op
    quests.admin.stats:
        description: View quest statistics of a player
        default: op
    quests.admin.give:
        description: Force a player to take a quest
        default: op
    quests.admin.quit:
        description: Force a player to quit a quest
        default: op
    quests.admin.points:
        description: Set a player's Quest Points
        default: op
    quests.admin.takepoints:
        description: Take away a player's Quest Points
        default: op
    quests.admin.givepoints:
        description: Add to a player's Quest Points
        default: op
    quests.admin.pointsall:
        description: Set ALL players' Quest Points
        default: op
    quests.admin.finish:
        description: Force a player to complete a quest
        default: op
    quests.admin.nextstage:
        description: Force a player to complete current stage
        default: op
    quests.admin.setstage:
        description: Set the current stage for a player
        default: op
    quests.admin.reset:
        description: Clear all Quests data of a player
        default: op
    quests.admin.remove:
        description: Remove a completed quest from a player
        default: op
    quests.admin.reload:
        description: Safely reload the plugin
        default: op
    quests.admin.drop:
        description: Ability to drop the Quests Journal
        default: op
    quests.editor.editor:
        description: Ability to open Quests Editor
        default: op
    quests.editor.create:
        description: Ability to create new quests
        default: op
    quests.editor.edit:
        description: Ability to edit existing quests
        default: op
    quests.editor.delete:
        description: Ability to delete existing quests
        default: op
    quests.events.editor:
        description: LEGACY - Ability to open Actions Editor
        default: op
    quests.events.create:
        description: LEGACY - Ability to create new actions
        default: op
    quests.events.edit:
        description: LEGACY - Ability to edit existing actions
        default: op
    quests.events.delete:
        description: LEGACY - Ability to delete existing actions
        default: op
    quests.actions.editor:
        description: Ability to open Actions Editor
        default: op
    quests.actions.create:
        description: Ability to create new actions
        default: op
    quests.actions.edit:
        description: Ability to edit existing actions
        default: op
    quests.actions.delete:
        description: Ability to delete existing actions
        default: op
commands:
    quests:
        description: Quests command
        permission: quests.quests
        aliases: qs
    questadmin:
        description: Quests admin command
        permission: quests.admin
        aliases: [questsadmin, qa]
    quest:
        description: Quest command
        permission: quests.quest
        aliases: q